services:
  # Backend API Service
  - type: web
    name: shopmart-api
    env: node
    region: frankfurt
    plan: free
    rootDir: apps/api
    buildCommand: npm ci --only=production
    startCommand: node src/server.js
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        sync: false
      - key: AUTO_SEED
        value: "true"
      - key: AI_ASSISTANT_URL
        sync: false

  # AI Assistant Service
  - type: web
    name: shopmart-ai-assistant
    env: python
    region: frankfurt
    plan: free
    rootDir: apps/ai-assistant
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8000"
      - key: PYTHON_VERSION
        value: "3.11.0"
